spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true